aurpublish: Improve code quality
* Circumvent $?
* Distinguish between array and strings more carefully
* Exit with an error if important cd commands fail

diff --git a/aurpublish b/aurpublish
--- a/aurpublish
+++ b/aurpublish
@@ -3,7 +3,7 @@
 # Help function, declare usage
 function usage() {
 	cat <<-EOF
-		Usage: ./$(basename $0) [OPTIONS] PACKAGE
+		Usage: ./$(basename "$0") [OPTIONS] PACKAGE
 		Manage AUR packages as git subtree
 
 		OPTIONS
@@ -16,11 +16,10 @@ function usage() {
 
 # Check for links in all packages which are using http but could be using https
 function check_https() {
-	[[ -n "$@" ]] && path=$@ || patch=(.)
-	for link in $((find ${path[@]} -type f -iname pkgbuild -exec pcregrep -iH "http[^s]" {} \;) | sed 's/.*http:\/\/\([^\/]*\).*/\1/g' | sort | uniq); do
+	[[ -n "$*" ]] && path=($@) || path=(.)
+	for link in $( (find ${path[@]} -type f -iname pkgbuild -exec pcregrep -iH "http[^s]" {} \;) | sed 's/.*http:\/\/\([^\/]*\).*/\1/g' | sort | uniq); do
 		echo -n "${link}: "
-		curl -s "https://${link}" >/dev/null
-		if [[ $? != 0 ]]; then
+		if ! curl -s "https://${link}" >/dev/null; then
 			echo -e "\e[31mFALSE\e[39m"
 		else
 			echo -e "\e[32mTRUE\e[39m"
@@ -50,8 +49,11 @@ function pull_packages() {
 }
 
 # Do the great option check
-PARAMS=$(getopt -o pshg: -l help,pull,check-https,git: -n "aurpublish" -- "$@")
-[[ $? -ne 0 ]] && >&2 echo "error: No arguments passed." && usage && exit 2
+if ! PARAMS=$(getopt -o pshg: -l help,pull,check-https,git: -n "aurpublish" -- "$@"); then
+	>&2 echo "error: No arguments passed."
+	usage
+	exit 2
+fi
 eval set -- "$PARAMS"
 while true; do
 	case "$1" in
@@ -89,21 +91,21 @@ while true; do
 	esac
 	shift
 done
-PACKAGE_ARRAY=($*)
+PACKAGE_ARRAY=($@)
 
 # Remove trailing slashes from each package (if they even have one)
-[[ -n "${PACKAGE_ARRAY[@]}" ]] && PACKAGE_ARRAY=("${PACKAGE_ARRAY[@]%/}")
+[[ -n "${PACKAGE_ARRAY[*]}" ]] && PACKAGE_ARRAY=("${PACKAGE_ARRAY[@]%/}")
 # Strip directory information
-[[ -n "${PACKAGE_ARRAY[@]}" ]] && PACKAGE_ARRAY=("$(basename -a ${PACKAGE_ARRAY[@]})")
+[[ -n "${PACKAGE_ARRAY[*]}" ]] && PACKAGE_ARRAY=("$(basename -a "${PACKAGE_ARRAY[@]}")")
 
 # Save current path to get back later
 previous_pwd="$(pwd)"
-cd "$(git rev-parse --show-toplevel)"
+cd "$(git rev-parse --show-toplevel)" || exit 1
 
 # Invoke the appropiate function to run the specified options
 if [[ "${CHECK_HTTPS,,}" == "true" ]]; then
 	check_https ${PACKAGE_ARRAY[@]}
-elif [[ -n "${PACKAGE_ARRAY[@]}" ]]; then
+elif [[ -n "${PACKAGE_ARRAY[*]}" ]]; then
 	# Running pull or push commands makes sense only if a packages was specified
 	if [[ "${PULL_SUBTREE,,}" == "true" ]]; then
 		pull_packages ${PACKAGE_ARRAY[@]}
@@ -116,4 +118,4 @@ else
 fi
 
 # Restore previous path
-cd "${previous_pwd}"
+cd "${previous_pwd}" || exit 1
